build.gradle, src/main/java/com/prgrms/mukvengers/domain/user/api/UserController.java, src/main/java/com/prgrms/mukvengers/domain/user/exception/UserNotFoundException.java, src/main/java/com/prgrms/mukvengers/domain/user/model/User.java, src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java, src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthentication.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationEntryPoint.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilter.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationToken.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java, src/main/java/com/prgrms/mukvengers/global/security/token/exception/ExceptionHandlerFilter.java, src/main/java/com/prgrms/mukvengers/global/security/token/exception/ExpiredTokenException.java, src/main/java/com/prgrms/mukvengers/global/security/token/exception/InvalidTokenException.java, src/main/java/com/prgrms/mukvengers/global/security/token/exception/TokenException.java, src/main/java/com/prgrms/mukvengers/global/utils/ExtractUtil.java, src/main/resources/application-security.yml, src/main/resources/application-test.yml, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/config/JwtConfig.java, src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/user/model/UserTest.java, src/test/java/com/prgrms/mukvengers/domain/user/repository/UserRepositoryTest.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationTest.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java, src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java, src/test/resources/application.yml
두가지 기능을 구현해서 하나의 PR로 만들어서 올렸습니다.. 빨리 구현해야 해서 같이 올린점 양해 부탁드립니다!
- JWT 의존성 설정(변경)
- com.auth0:java-jwt => io.jsonwebtoken:jjwt 변경
- jjwt가 레퍼런스가 더 많고 손 쉽게 사용가능해서 변경했습니다 
- TokenException 계층
- Security에서 발생할 수 있는 Token 관련 예외 추상화
- InvalidTokenException: 올바르지 않은 토큰인 경우 발생할 수 있는 예외 (시크릿 키가 다르거나, 정상적이지 않은 JWT 형태,등 시큐리티에서 JWT 관련으로 나타날 수 있는 예외)
- ExpiredTokenException: 정상적인 토큰이지만 만료 시간이 지난 토큰을 사용할 때 발생하는 예외
- JwtAuthenticationFilter
- 시큐리티 인증 필터
- 헤더에 accessToken이 있을때 동작
- 토큰이 유효하지 않으면 예외 발생
- 유효한 토큰 존재시 인증 객체 만들어서 SecurityContextHolder에 넣어줌
- 테스트 코드 추가했습니다. 동작을 확인해보셔도 좋을 것 같아요
- JwtAuthenticationToken
- 인증 객체를 담는 그릇: 시큐리티 필터에서 인증 객체를 전달하는데 사용됨
- 인증 사용자 객체, credentials(자격 증명서), 권한
- DTO 역할인 것 같아서 따로 테스트를 작성하지는 않았습니다
- JwtAuthentication
- 인증된 사용자를 의미하는 객체
- id, accessToken을 필드로 가짐
- 추후에 변경해볼 예정
- …
=> [#8, #3] JWT 기반 인증 기능 및 유저 Controller 구현

src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java, src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/OAuthUserInfo.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/HttpCookieOAuthAuthorizationRequestRepository.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandler.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/mapper/OAuthMapper.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthProvider.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthService.java, src/main/java/com/prgrms/mukvengers/global/utils/CookieUtil.java, src/main/resources/application-security.yml
- [config(Security): application-security.yml에 구글 OAuth 설정 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/097a3b73a14f3f0fb070057fa4332fbd84a4f475)
- client-id, client-secret 추가
- 구글과 카카오 변수 구분하기 
- [feat(OAuth): 리소스 서버에서 받아온 데이터를 변환하는 기능(객체)들 구현](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/bb7cfa4dddc16d37d4bd1371e3dbf749ba1842a7)
- OAuthProvider: 리소스 서버에 맞게 OAuth2User -> OAuthUserInfo 로 변환하는 역할
- ENUM으로 관리 (팀원과 상의 후 결정)
- HashMap으로 최적화 적용
- 리뷰 포인트: 가독성이 떨어지는 확인 바람
- getOAuthProviderByName에서 발생하는 예외 변경 필요할 듯(추후 고려)
- OAuthUserInfo: 리소스 서버에서 받아온 데이터를 전달하기 위한 DTO
- OAuthMapper: OAuthUserInfo -> User로 변환하는 Mapper
- UserMapper에 있어야 하는지 고민 중(추후 리팩터링 고려 사항)
- [feat(OAuth): 로그인 기능 …
=> [#28] OAuth를 이용해서 kakao 및 google 로그인 기능 구현 

.platform/nginx/nginx.conf
- Route53에 도메인 등록 및 SSL 인증서 발급
- Elastic Beanstalk에 로드 벨런서 구성 후 SSL 인증서 적용
- nginx 설정을 변경하여 http(80포트)의 요청을 https(443포트)로 리다이렉트합니다.
- `http_x_forwarded_proto` 헤더는 클라이언트가 접속할 때 사용한 프로토콜을 나타냅니다.
- 관련해서 간단하게 문서로 남기겠습니다.
=> [#39] prod서버에 SSL 인증서 도입 

src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java, src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/main/java/com/prgrms/mukvengers/domain/review/api/ReviewController.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateLeaderReviewRequest.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateMemberReviewRequest.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/response/ReviewResponse.java, src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java, src/main/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepository.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewService.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java, src/test/java/com/prgrms/mukvengers/base/ServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java, src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java
- 방장에 대한 매너온도와 맛잘알 리뷰를 생성할 수 있다.
- 방장이 아닌 일반 밥모임원 대한 매너온도 리뷰를 생성할 수 있다.
- 리뷰의 단건 조회
- RestDocs로 API 문서화
작성해보니깐` crewMemberRepository.findCrewMemberByCrewId` 필요없을꺼 같은데 어떻게 생각하시나요?
resolves #15 #16
=> [#15] 방장과 밥모임원에 대한 매너온도 및 맛잘알 리뷰 생성 및 조회

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/DistanceRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
- RequestParam을 ModelAttribute로 변경하였습니다.
- 파리미터로 거리를 받로록 추가하였습니다.
- 거리계산이 500미터 고정값에서 파라미터로 받은 거리 이하의 모임을 계산하여 조회합니다.
resolves #54
=> [#54] 검색 범위 거리를 프론트에서 파라미터로 받도록 수정 

src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/dto/AuthUserInfo.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/service/OAuthService.java, src/main/java/com/prgrms/mukvengers/global/security/token/api/TokenController.java, src/main/java/com/prgrms/mukvengers/global/security/token/dto/request/CreateAccessTokenRequest.java, src/main/java/com/prgrms/mukvengers/global/security/token/dto/response/TokenResponse.java, src/main/java/com/prgrms/mukvengers/global/security/token/exception/RefreshTokenNotFoundException.java, src/main/java/com/prgrms/mukvengers/global/security/token/model/Token.java, src/main/java/com/prgrms/mukvengers/global/security/token/repository/TokenRepository.java, src/main/java/com/prgrms/mukvengers/global/security/token/service/TokenService.java
- 현재는 기능의 일부만 구현하였습니다. 
- 다만, 기능의 기반을 구현하였기 때문에 **전반적인 리뷰를 거치고 리팩터링하고 필요한 설정을 추가하여 정상동작이 될 수 있게 하겠습니다.**
- 현재 예상되는 PR의 순서는 `기능 구현 -> 리팩터링 -> 레디스 설정 -> 테스트 작성 -> 완료 `입니다.
- [feat(Token): refreshToken을 전달하기 위한 응답 DTO 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/089abbcfaf19c7fe8bbe7bfada604ab5016c20d3)
- refreshToken을 통해 새로운 accessToken을 요청했을 때 새로운 accessToken과 refreshToken 둘다 전달
- refreshToken이 만료되지 않는 이상 계속 로그인 가능하도록 하는 방식으로 구현
- [feat(Token): RefreshToken을 통해 새로운 accessToken을 받기 위한 요청 DTO 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/b402b5dce406545c0ea9c0199c601e18e3baac1f)
- [feat(Token): refresh을 저장하기 위한 Token 객체](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/6a90d6f3ece9c6b123dcbe006b44defe17a14b54) …
=> [#38] Refresh Token 기능 구현

build.gradle, docker-compose.yml, src/main/java/com/prgrms/mukvengers/global/config/redis/RedisConfig.java, src/main/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProvider.java, src/main/java/com/prgrms/mukvengers/global/security/token/model/RefreshToken.java, src/main/java/com/prgrms/mukvengers/global/security/token/repository/RefreshTokenRepository.java, src/main/resources/application-db.yml, src/main/resources/application-security.yml, src/main/resources/application-test.yml, src/test/java/com/prgrms/mukvengers/config/JwtConfig.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtTokenProviderTest.java
- [feat(Redis): 레디스 의존성 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/1d29cb502f16c4a7988fd82bb1c065ebe39b75f7)
- 스프링 부트에서 제공하는 `spring-boot-starter-data-redis` 사용
- [feat(Redis): 레디스 host 및 port 설정](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/4175e084e7bec1bbd29eb8d99e3adb4ae88ba90a)
- 프러덕션 코드는 `host`와 `port`를 환경 변수로 관리
- 테스트는 localhost로 사용하고 port는 디폴트 포트인 **6379**로 사용
- 실행시키기 위해서는 도커로 레디스를 설치해야 합니다
- [feat(Token): RefreshToken 만료 시간 설정](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/5eff9c30fa250efbce114a8d2003b91ab07fb944)
- `360000초`(100시간)로 설정
- [feat(Token): JwtTokenProviderdp RefreshToken 만료 시간 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/69722988a483681b4ef086551afe723f …
=> [#38] RefreshToken 기능에 Redis 적용

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/MyCrewResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/test/java/com/prgrms/mukvengers/base/ServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 사용자가 참여한 모든 모임 조회 기능 구현, 테스트
- 프런트의 요청 사항으로 현재인원을 조회하기 위해 모임원 Repository에서 모임 아이디로 조회를 하여 현재인원을 count 하여 리턴합니다.
- 프런트의 요청으로 조회된 모임을 모집 중인 데이터를 먼저 오게 정렬하고 모집 종료된 모임이 나중에 오도록 정렬합니다.
- 프런트의 요청으로 현재 사용자의 프로필 이미지도 리턴합니다.
- CrewResponse에서 현재인원 필드 추가하였습니다.
- 
- 프론트의 요청으로 이미지 URL을 리턴해주어야 되서 새로운 응답 DTO MyCrewResponse를 만들었습니다.
- 이 DTO 네이밍이 어떠신지 궁금합니다.
- 
resolves #65
=> [#65] 사용자의 밥 모임 조회

build.gradle, src/main/java/com/prgrms/mukvengers/global/aws/api/AwsS3Controller.java, src/main/java/com/prgrms/mukvengers/global/aws/dto/AwsS3.java, src/main/java/com/prgrms/mukvengers/global/aws/service/AwsS3Service.java, src/main/java/com/prgrms/mukvengers/global/config/s3/AwsConfig.java, src/main/resources/application-aws.yml, src/main/resources/application.yml, src/test/resources/application.yml
@JoosungKwon  주성님이랑 같이 S3 작업하다가.. 제가 그만 git 시간여행에 실패해서... 새로운 branch를 파서 PR 날립니다..
- `/s3/resource  POST`: 프로필 이미지를 변경하는 요청이 올 때 S3에 이미지 파일을 저장하고, S3의 URL(path)과 업로드된 이미지의 객체명(key)을 담은 AwsS3 Dto를 반환합니다.
- `/s3/resource DELETE`: 프로필 이미지를 삭제하는 요청의 경우 key값을 이용해 S3에서 이미지 파일을 삭제합니다.
- 프로필 이미지 외에 다른 곳에서 S3를 사용할 수도 있다고 판단하여 
패키지 구조를 global>aws>api, service로 설정했습니다.
- `bucket`: AWS S3에서 직접 생성한 스토리지 창고 이름입니다. kkini-bucket으로 설정했으며 이곳에 저장된 이미지의 URL은 kkini-bucket으로 시작합니다. 
- S3에 업로드하기 위해서는 프론트로부터 이미지 파일을 받은 뒤(MultipartFile 타입이며 컨트롤러에서 받고 있습니다)
이를 File 객체로 변환후 현재 프로젝트 경로에 업로드 합니다. 
이후 파일명에 UUID를 붙혀서 S3에 업로드하고, 현재 경로에 생성한 File 객체를 삭제하는 과정을 거칩니다.
- 이해 안되는 부분이나 개선할 수 있는 부분 말씀해주시면 감사하겠습니다!!!
저장 요청 시 Response
#77
=> [#77] 사용자 프로필 이미지를 S3에 저장한다.

src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
- 외부자원 요청시, 사전 요청으로 OPTION 메서드를 사용해서 보내기 때문에 허용 메서드에 추가 해야할 필요가 있었음
- 프론트의 요청으로 긴급 해결사항(HOTFIX)
- 적용 중 에러 발생 해결 (참고: https://kim6394.tistory.com/273)
=> CORS 설정에 OPTIONS 메서드 추가

src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 모임 생성시 가게 정보를 같이 받아 가게 데이터가 없으면 가게 정보를 DB에 저장합니다.
- 모임 생성 DTO 수정
- 모임 생성 로직 수정
- resolves #105
=> [#105] 모임 생성시 가게 정보가 없을 경우 가게를 저장한다.

build.gradle
- 빌드 스크립트에 jar 작업시에 plain 파일 생성 제외 동작 추가
- build.gradle에서 jar 작업시에 plain 파일 생성 제외
- 참고 자료
- https://earth-95.tistory.com/132
- https://wonyong-jang.github.io/devops/2022/07/17/DevOps-gradle.html
=> [#24] cp: target 'deploy/application.jar' is not a directory 문제 해결

src/main/resources/db/migration/V3.0__alter_store_table.sql, src/test/resources/schema.sql
가게의 photo_urls DB 컬럼 데이터 타입 varchar(255) -> TEXT로 수정
- 추후에 카테고리, 사진 URL은 테이블을 따로 만들어야 겠습니다.
- resolves #113
=> [#113] 가게 이미지 Url DB 저장 데이터 타입 수정

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
- 사용자의 아이디로 신청서 테이블의 작성자 컬럼과 일치하는 모든 신청서 데이터를 조회합니다.
- resolves #98
=> [#98] 사용자가 참여를 위해 작성한 신청서 조회 

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
- crewId를 ResponseBody에 담아 보내도록 수정
- 저희 모든 create api에서 body를 린턴이 IdResponse로 되어있지만 실제로 담아주지 않는데 저희가 놓치고 있는 거 아닌지 궁금합니다.
resolves #120
=> [#120] 모임 생성시 ResponseBody에 모임 아이디를 반환

src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateLeaderReviewRequest.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateMemberReviewRequest.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/response/ReviewResponse.java, src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java, src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java, src/test/resources/schema.sql
- `작성자(Reviewer)`와 리뷰하고자 하는 받는이`(Reviewee)`의 아이디를 나타내는 필드명이 reviewer, reviewee 로
컬럼명을 보았을 때 **아이디 값을 가진다는 것**을 알기 어렵기 때문에 각각 `reviewer_id, reviewee_id`로 변경하였습니다.
- User 테이블에서는 mannerScore와 tasteScore 로 Reivew 테이블에서는 mannerPoint, tastePoint 로 각각 다른 컬럼명을 사용하고 있었기 때문에 `mannerScore`, `tasteScore`라는 이름으로 통일하도록 변경하였습니다.
- mannerScore, tasteScore 필드명 변경으로 인한 프로덕션 코드 및 테스트 코드 수정하였습니다.
- 리뷰 컨트롤러 tag, summary, description, schema 컨벤션 적용하도록 수정하였습니다.
- 혹시 빠진 컨벤션이 있다면 말씀해주세요!
resolves #116
=> [#116] Review 필드명 수정 및 Review Controller 테스트 컨벤션 리팩토링

src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java
- 프론트와 `refreshToken`을 원활하게 주고 받기 위해 `Cookie`설정에서 `SameSite` 값을 **`None`** 으로 변경하였습니다.
- `Cookie` 클래스보다 다양한 설정을 할 수 있는 **`ResponseCookie`** 클래스를 사용했습니다.
- [fix(Web): 쿠키에 sameSite 설정을 none으로 바꾸기](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/13b229c99f5955b8b79296e87f9d1201e75b1c24)
- `참고 자료`: https://kindloveit.tistory.com/100
- #38
=> [#8] Cookie에 SameSite 설정을 None으로 변경

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponses.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
- 사용자의 위경도를 받아 모임을 조회하는 응답 객체가 위도, 경도, 가게아이디를 반환하도록 수정하였습니다.
- 사용자의 거리 기반 모임 조회 api 에서 모임의 정보와 모임원의 정보가 필요하지 않아 수정합니다.
- 응답에 위도, 경도에 대한 값이 없어 추가하였습니다.
- 가게를 조회 할 수 있도록 가게 아이디를 전달 값에 추가하였습니다.
- resolves #123
=> [#123] 사용자 거리기반 모임 조회 응답 값 수정 

src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewDetailResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java
- 프론트의 요청으로 가게의 모임조회, 사용자가 참여한 모임 조회, 모임 단건 조회 응답에 가게 정보도 같이 반환합니다.
- CrewDetailResponse에서 StoreResponse 필드 추가
- DTO 수정에 요청이 계속 오는데 변화에 잘 대응하지 못하는 것 같습니다.
- 리스트를 일급컬렉션으로 만들어 반환하고 있는데 컬렉션을 한번 Wrapping하는 것이 옳은 것인지 모르겠습니다. 팀원분들의 생각이 궁금합니다.
resolves #127
=> [#127] 모임 단건 조회 응답 DTO 수정

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/dto/request/CreateProposalRequest.java, src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewMemberObjectProvider.java, src/test/java/com/prgrms/mukvengers/utils/ProposalObjectProvider.java
- 신청서를 작성하는 API를 생성하였습니다.
- 신청서를 생성하기 전 `여러 검증`이 필요합니다.
- 사용자가 존재하는 사용자인지 & 밥모임이 존재하는 밥모임인지
- 해당 밥모임의 모집 인원이 다 차서 신청할 수 없는 경우
- 이미 신청한 밥모임에 다시 신청서를 작성하는 경우 (중복 신청 방지)
- 강퇴된 사용자가 해당 밥모임에 다시 신청하는 경우 (강퇴 유저)
- 해당 밥모임의 방장이 신청서를 작성하는 경우
- 각 검증에 대한 실패 테스트를 작성하였습니다.
- CrewMemberRole에 따른 검증은 `메시지만 다르지 똑같은 예외`가 터지는 것이라 생각해 `IllegalStateException` 처리한 상태입니다. 
따로 Custom Exception으로 처리하는 것이 좋을까요? 그렇다면 총 Exception 클래스는 4개가 나올 것으로 예상되며
[feat: Custom Exception 으로 변경시 사용될 ErrorCode](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/228e75cd3b6392245b7b02f83837ad1b132b20ba) 처럼 `HttpStatus.FORBIDDEN` 상태 코드를 두려고 하는데 어떻게 생각하시나요?
- 혹시 제가 빠트린 다른 검증 로직이 있을까요?
resolves #126
=> [#126]  신청서(proposal) 작성 API 생성

src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java, src/main/java/com/prgrms/mukvengers/global/security/token/api/TokenController.java, src/main/java/com/prgrms/mukvengers/global/utils/CookieUtil.java
- httpOnly 속성은 브라우저에서 Cookie정보를 사용할 수 있게 하는 옵션입니다. false로 설정할 경우 브라우저(JS)에서 Cookie 값을 사용할 수 있습니다. 그렇게 된다면 악의적인 크롤러에 의해서도 탈취되거나 사용할 수 있게 되기 때문에 별로 좋지 않습니다. 물론, secure 속성은 true이기 때문에 암호화 되어 있습니다. 그럼에도, 위험하기 때문에 추후에 LocalStorage를 이용할 수 있는 방법을 적용해볼 수 있도록 하겠습니다.
- #38
=> [#38] Cookie httpOnly 속성 변경

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/UpdateStatusRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 모임 상태를 모집 종료 -> 식사 완료로 변경합니다. 
- 모집 중 -> 모집 종료 api와 코드가 매우 비슷합니다. 
- 하나의 api로 처리하고 메서드 안에서 분기로 나누는것을 고민하고 있습니다.
- 팀원분들은 어떻게 생각하시나요? 더 좋은 방법이 있을까요?
- resolves #135
=> [#135] 모집 상태 변경(모집 종료-> 식사 완료) 기능

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
- update 메서드명 updateProposalStatus로 변경하였습니다.
- 수락/거절하는 상태 변경 API userId -> leaderId로 변경하였습니다.
- 사용하지 않는 error 코드 삭제하였습니다.
- 빠진 부분 있는지 확인해주세요!
resolves #143
=> [#143] 신청서(Proposal) 수락/거절 상태값 변경 API 수정 및 기타 수정

build.gradle
- 프론트에서 Swagger 확인시에 API창이 열려 있는게 불편하다고 닫혀있는 상태로 변경을 요청하셔서 일단은 Gradle에서 설정하는 방법을 몰라서 하드 코딩으로 생성후 글자를 변경하는 방식으로 요구 사항을 반영했습니다.
- [refactor(Build): Swagger UI에서 docExpansion 설정 'none'으로](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/bf8a61cc9547bb917ec29ab0d515f244e67a5339)
- [refactor(Build): Swagger UI에서 docExpansion 설정 'none'으로 변경](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/8e106eb95649b2bcb0a8877ba150f3b36cd56018)
- #148
=> [#148] Swagger UI에서 docExpansion 설정 'none'으로 변경

build.gradle
- 이전 PR(#149)에서는 bootJar에만 동작하여 jar파일에는 적용이 안되었던 것 같아서 copySwaggerUI Task 후 진행할 수 있도록 수정했습니다
- #148
=> [#148] Swagger UI의 docExpansion 설정을 jar 파일에도 적용

src/main/java/com/prgrms/mukvengers/domain/chat/api/ChatController.java, src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatResponse.java, src/main/java/com/prgrms/mukvengers/domain/chat/dto/response/ChatResponses.java, src/main/java/com/prgrms/mukvengers/domain/chat/repository/ChatRepository.java, src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatService.java, src/main/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/chat/service/ChatServiceImplTest.java
- crewId를 이용해 밥모임의 채팅 정보를 가져오는 API를 추가했습니다.
- 기존에 존재하는 API는 Pageable을 Request로 받아서 처리합니다.  시연할 때 편의를 위해 전체 조회하는 API를 요청하셔서 생성하게 되었습니다.
- 기존 Pageable을 받는 API는 v2로 변경해두었습니다.
- resolves #165
=> [#165] 밥모임의 채팅내역을 조회하는 api 추가

src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/global/scheduler/Scheduler.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java
- 시간이 지난 모임 삭제 메서드를 추가했습니다.
- 쿼리는 테스트 코드를 통해서 확인 했습니다.
- [feat(Crew): 시간이 지난 모임 삭제 메서드 추가](https://github.com/prgrms-web-devcourse/Team-DarkNight-Kkini-BE/commit/96433f2a1b89e0c64c5a054d23fccfebfb205888)
- Spring에서 제공하는 @Scheduled을 통해서 스케줄링 작업을 구현했습니다.
- 매시각 정각에 앞서 만든 `시간이 지난 모임 삭제 메서드`를 실행합니다.
- 스케줄링 작업은  정각에 실제 동작하는지 직접 확인 했습니다. 
- [feat(Schedule): 매일 1시간 마다 동작하는 스케줄 작성](https://github.com/prgrms-web-devcourse/Team-DarkNight-Kkini-BE/commit/b86e9e1d10a5c4b81b577abf2da27c968e88829d)
- [참고자료] [Scheduler 사용해보기](https://data-make.tistory.com/699)
- `updateStatusAll` 라는 메서드 명이 괜찮은가요..?
- 주기는 크루가 많지 않다는 가정하에` 1시간`으로 설정 했는데 어떻게 가져가면 좋을지 의견 부탁드립니다.
- 개인적으로는 `10분 ~ 1시간 사이`로 가져가도 괜찮을 것 같다고 생각합니다. 
- 왜냐하면 한번에 많이 하게 되면 `batch size`도 고려해야하기 때문입니다. 
- 짧게 여러번 가져가도록 **`일단`** 구현하고 `이슈에 따라 적절히 변경`하는 것은 …
=> [#169] 모임 상태 자동 변경 프로세스 구현

.github/workflows/deploy-to-dev.yml, deploy.sh, docker-compose.yml
- blue/green 방식의 무중단 배포 적용
- 기존의 github action에서는 docker-compose up -d로 컴포즈에 등록된 모든 컨테이너를 한방에 실행했습니다.
하지만 현재 `docker-compose.yml`을 보시면 `blue(8081포트)/green(8080포트)`로 springboot 이미지가 두 개 등록되어 있어서, 
`deploy.sh`에 작성한 배포 스크립트를 실행시키는 방식으로 명령어를 변경했습니다.
`deploy.sh`: 
- db와 redis가 중지상태면 실행시킵니다. 
- 이후 현재 실행중인 컨테이너를 조회합니다.  `$(docker ps | grep green)` 
간단히 설명하고자 현재  **blue 컨테이너**가 **실행중**인 상태라고 하겠습니다.
- CI된 SpringBoot 이미지는 Docker hub에 저장됩니다. 이 이미지를  EC2의 docker에서 **green** 으로 pull 받고 실행시킵니다.
- **green**  컨테이너 실행 후 SpringBoot가 정상 실행되어 health check가 종료되면 `nginx.conf`의 내용을 nginx.blue.conf에서 **nginx.green.conf** 로 변경합니다(각각의 nginx는 443포트로 들어오는 요청을 8081, 8080 포트로 보내줍니다). 
- **blue** 컨테이너를 종료합니다.
- 이제 **green**이 실행중이므로 바로 다음 deploy에서는 **blue**에 업데이트가 되며 nginx.blue.conf을 사용하게 됩니다.
- 참고 링크: …
=> [#174] 무중단 배포 적용

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationFailureHandler.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/handler/OAuthAuthenticationSuccessHandler.java, src/main/java/com/prgrms/mukvengers/global/security/oauth/repository/HttpCookieOAuthAuthorizationRequestRepository.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
- OAuth 요청시에 redirect_uri를 저장하기 위해 쿠키를 사용하고 있습니다.(HttpCookieOAuthAuthorizationRequestRepository)  
- 프론트에서 redirect_uri에 쿼리를 함께 보내고 있습니다. 
- 쿼리 중에서 "name" (가게 이름) 에 한글이 들어갑니다.
- 따라서, 한글로 이루어진 uri를 쿠키에 저장할 수가 없어서 에러가 발생하게 됩니다.
- 해당 문제는 쿠키에 저장하기 전에 인코딩 과정을 추가하고 다시 쿠키에서 가져올 때 디코딩 과정을 추가함으로서 해결하였습니다.
- 참고: [쿠키(Cookie)에 한글 데이터 저장하고 가져오기](https://dololak.tistory.com/537)
- 위와 비슷한 맥락입니다.
- 쿠키에서 꺼내온 redirect_uri에 쿼리 파라미터로 한글이 들어가 있기 때문에 정상적으로 Redirect가 안되었습니다.
- 해당 문제는 **`"name="`** 을 기준으로 Split 한후에 파라미터에 해당하는 부분(가게 이름)만 따로 한번 더 인코딩한 후에 프론트에 전달하여 해결했습니다.
- 참고: [Redirect 시 한글 파라미터가 깨지는 문제](https://ivvve.github.io/2019/01/20/java/Spring/redirect_URL_encoding/)
- 일단 현재 문제가 되는 쿼리는 `name` 뿐이라서 하드 코딩으로 구현 했는데 좀 더 범용성 있는 방식을 사용하고자 하는데 좋은 아이디어나 알고리즘이 있다면 제안 부탁드립니다~!
- resolves #186
=> [#186] redirectUri에 한글이 들어가면 에러 터지는 문제 해결

src/main/java/com/prgrms/mukvengers/domain/user/dto/response/UserProfileResponse.java, src/main/java/com/prgrms/mukvengers/domain/user/model/User.java, src/main/resources/db/migration/V4__alter_user_table.sql, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/user/model/UserTest.java, src/test/java/com/prgrms/mukvengers/domain/user/service/UserServiceTest.java, src/test/resources/schema.sql
브랜치를 잘못 관리해서 새로운 PR 날립니다. 죄송합니다🫠
- UserProfileResponse 클래스의 매너 온도(mannerScore) 타입을 `Double`에서 `String`값로 변경
- API 응답 시 혹시 모를 **소수점 이하에서의 데이터 유실을 확실하게 예방하기 위해 문자열**로 응답하였습니다.
- 그와 관련된 Controller 테스트에서의 mannerScore 타입을 type(NUMBER) 에서 type(STRING) 으로 변경하였습니다.
- User 클래스의 매너 온도(mannerScore)의 타입을 `Double`에서 `BigDecimal`로 변경
- float과 double 타입은 부동 소수점으로 **정확한 값이 아닌 근사치**를 나타내서 데이터 **정확도 문제**가 발생할 수 있습니다.
- 이로인해 사칙 연산 시 **기대한 값과 다른 값을 출력하는 경우가 생길 수 있어** Double에서 BigDecimal로 변경하였습니다.
- 물론, mannerScore의 소수 2번째 자리를 반올림하여 mannerScore를 소수 1번째 자리까지 저장하면 해결할 수 있지만,
사칙 연산 처리하여 해결하기 보다는 BigDecimal를 사용하여 보다 더 정확한 값을 관리하고 싶어 사용하였습니다!
- [BigDecimal 참고 자료](https://jsonobject.tistory.com/466)
- User 클래스의 addMannerScore 메소드에서 **매너 온도가 음수값이 되지 않도록 checkMinusMannerScore** 메소드를 통해 유효성 검증
- User 클래스의 **기존 …
=> [#179] User 매너 온도 BigDecimal 타입으로 변경하여 소수점 에러 해결
