.github/workflows/ci-gradle-build.yml
- GitHub Actions 빌드 스크립트 작성 
- 빌드시 캐시 적용
- 추후에 jacoco, sonarCloud 적용도 고려해봐야 할 것 같습니다!
- CI에 대해서 다같이 공부가 필요할 것 같아요
#4
=> [#4] CI - GitHub Actions를 활용해서 Gradle Build 적용

src/main/java/com/prgrms/mukvengers/domain/user/dto/request/UpdateUserRequest.java, src/main/java/com/prgrms/mukvengers/domain/user/dto/response/UserProfileResponse.java, src/main/java/com/prgrms/mukvengers/domain/user/exception/UserNotFoundException.java, src/main/java/com/prgrms/mukvengers/domain/user/mapper/UserMapper.java, src/main/java/com/prgrms/mukvengers/domain/user/model/User.java, src/main/java/com/prgrms/mukvengers/domain/user/repository/UserRepository.java, src/main/java/com/prgrms/mukvengers/domain/user/service/DefaultUserService.java, src/main/java/com/prgrms/mukvengers/domain/user/service/UserService.java, src/main/java/com/prgrms/mukvengers/global/common/domain/BaseEntity.java, src/main/java/com/prgrms/mukvengers/global/common/dto/ErrorResponse.java, src/main/java/com/prgrms/mukvengers/global/common/dto/IdResponse.java, src/main/java/com/prgrms/mukvengers/global/config/jpa/JpaConfig.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java, src/main/java/com/prgrms/mukvengers/global/exception/ServiceException.java, src/main/resources/db/migration/V1__init.sql, src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/user/repository/UserRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/user/service/UserServiceTest.java, src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java, src/test/resources/schema.sql
- Service 및 Repository 레이어 구현 
- 테스트 코드 작성
- 추후에 소셜 로그인 기능 구현한 후에 유저 생성과 Controller(API)를 구현하겠습니다.
- 테스트 코드 작성을 봐주세요.
- 서비스 로직을 검토해주세요.
- 추가적으로 예외 관리 흐름에 대해 검토해 주세요
#3
=> [#3] 유저 RUD 기능 구현

.github/workflows/ci-gradle-build.yml, src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java, src/main/resources/application-test.yml, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java, src/test/resources/application.yml, src/test/resources/schema.sql
- [config: application.yml에 DB 변경 반영하기](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/4133c583eec334a8486800e77586bc22e3e1dc71) 
- [refactor(test): AutoConfigureTestDatabase 설정 바꾸기](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/5ff91e1f1574ea3949a47b7f71a316c3ef3640a6)
- [fix: Store @ColumnTransformer 주석 해제 및 내용 수정](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/d0293e34a9d1e229669e9b6d5e026a996e77fcbe)
- 제 로컬에서 정상 동작했습니다. 브랜치에서 각자 실행 해보고 문제 있으면 알려주세요! 
resolves #22
=> [#22] 테스트 DB 환경을 인메모리 기반 H2에서 로컬(외부) MySQL로 변경

.github/workflows/deploy-to-aws.yml
=> [#24] Release Kkini v1.0.0

.github/workflows/ci-gradle-build.yml, .github/workflows/deploy-to-dev.yml, src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java, src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/global/security/jwt/JwtAuthenticationFilterTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 머지 하면서 생겨난 중복 코드 및 기타 수정이 필요한 사항을 수정했습니다.
- 로컬에서는 현재 이상이 없습니다.
- [config(Security): path: "/docs" 인증 절차 제외하기](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/d163c3f54b1084678708121e768552968ea6b867)
- [test(Jwt): Jwt 테스트 토큰 만료 시간 변경](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/fab4a321dec52294f3b847404c87ee42ee8676a8)
- [refactor(CI/CD): CI/CD 과정에서 동작할 이벤트 변경](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/7f03b62891c2220f7c238c698efe51c704ecdfe3)
- [refactor(Crew): 약속 시간(promiseTime) 필드 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/832253a2e04b40f4abea84e6734349ceb0b1c36a)
#24
=> [#24] 기타 오류 해결하기

docker-compose.yml
docker-compose 에 nginx 설정을 제거했습니다.
#36 원인과 해결은 이슈에 적어두었습니다!
=> [#36] docker-compose 수정

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewPageResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewSliceResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
- 오프셋 기반 페이지네이션으로 변경
- 주성님이 오늘 아침 말씀해주신 Swagger 내용을 적용하였습니다. 잘적용하였나요?
-  쿼리 어떠신가요?
resolves #42
=> [#42] 페이지네이션 수정

src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
- 코드 스타일이 아닌 Swagger 문서상에 좀 더 상세한 설명이 나올 수 있도록 함
- MockMvcRestDocumentationWrapper
- ResourceDocumentation
- ResourceSnippetParameters
수정 내용을 참고해서 사용법을 익히시면 됩니다. 사용법을 잘 모르겠으면 댓글이나 DM 주세요
-  설명은 간략하게 했습니다. 추가하고 싶은 설명이 더 있다면 알려주세요!
#24
=> [#24] Swagger 문서에 상세한 설명이 나올 수 있도록 테스트 수정

src/main/resources/db/migration/V2.5__alter_store_table.sql
- 가게 테이블 컬럼 추가(가게 이름, 카테고리, 도로명 주소, 구글 평점, 사진 URL, 카카오 지도 URL, 가게 전화번호)
- 카테고리와 사진 URL이 String 배열로 넘어옵니다.
- 배열을 저장할때는 몇가지 방법을 생각할 수 있습니다. 
- 배열을 하나의 String으로 받아 저장한다.
- URL, 카테고리 테이블을 따로 만들어 정규화한다.(Join 하여 데이터를 가져온다.)
- 저는 이중 1번 String으로 받아 저장한다를 선택하였습니다. 
- 프론트분들에게 요청하여 배열대신 String으로 넘겨보는걸 회의해볼 생각입니다.
- 2번 방법도 무난한 방법이라고 생각합니다. 이렇게 될 경우 별도의 테이블을 추가적으로 생성해야 합니다.
- 여러분들의 생각이 궁금합니다.
resolves #56
=> [#56] 가게 테이블 컬럼 추가

src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/store/api/StoreController.java, src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java, src/main/java/com/prgrms/mukvengers/domain/store/mapper/StoreMapper.java, src/main/java/com/prgrms/mukvengers/domain/store/service/StoreService.java, src/main/java/com/prgrms/mukvengers/domain/store/service/StoreServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java
- 맵 api id로 가게 단건조회 기능 구현
- 위도, 경도 타입 수정 String->Double
resolves #58 #13
=> [#58] 가게 아이디로 가게 조회 기능 구현

src/main/resources/db/migration/V2.6__delete_crewMember_column.sql, src/main/resources/db/migration/V2.7__alter_review_table.sql, src/test/resources/schema.sql
- crewMember: ready, blocked column 삭제
- review: store_id FK 삭제 후 crew_id 컬럼명으로 변경
- review: crew_id FK 추가
- review: crew_name column 삭제
- 테스트 DB 변경
- Review와 관련된 DB만 수정한 것이라 Comment와 Proposal 테이블 수정은 하지 않았습니다.
Review 리팩토링 후 추가하도록 하겠습니다
- ERD 보면서 빠진 부분있는지 확인 한번만 부탁드립니다!
resolves #61
=> [#61] Flyway를 이용해 crewMember, review 테이블 수정

src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/request/CreateLeaderReviewRequest.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/response/ReviewResponse.java, src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java, src/main/java/com/prgrms/mukvengers/domain/review/model/Review.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewMemberObjectProvider.java, src/test/java/com/prgrms/mukvengers/utils/ReviewObjectProvider.java, src/test/java/com/prgrms/mukvengers/utils/UserObjectProvider.java, src/test/resources/schema.sql
- crewMember:  block, ready 필드 삭제
- review: store, crewName 필드 삭제
- review: crew 필드 추가
- reviewObjectProvider: store, crewName 필드 삭제
- ReviewObjectProvider: crew 필드 추가
- CrewMemberObjectProvider 클래스 추가
- UserObjectProvider: 파라미터로 OAuth ID 받는 User 생성 메서드 추가
- ReviewObjectProvider: role 적용
- 네이밍이나 컨벤션 적용 안된 부분이 있는지 확인해주세요!
resolves #67
=> [#67] DB 변경으로 인한 CrewMember, Review Entity 수정 및 ObjectProvider 추가

src/main/resources/db/migration/V2.8_modify_erd_sprint3.sql, src/test/resources/schema.sql
- 신청서 테이블, 댓글 테이블 추가, test Schema 수정
resolves #64
=> [#64] 데이터베이스 수정

src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java, src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java, src/main/java/com/prgrms/mukvengers/domain/store/mapper/StoreMapper.java, src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java, src/main/resources/db/migration/V2.5__alter_store_table.sql, src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java, src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java, src/test/resources/schema.sql
- DB 수정에 따른 Store 필드 추가, 테스트 Schema 수정, 비즈니스코드, 테스트 코드 수정
- ERD 내용과 불일치하는 부분이 있는지 확인 부탁드립니다.
resolves #71
=> [#71] 테스트 스키마 변경하고 코드 수정

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Category.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/Status.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 모임 아이디로 모임 단건조회 기능 구현, 테스트
resolves #62
=> [#62] 모임 단건 조회

src/main/java/com/prgrms/mukvengers/global/config/web/WebConfig.java
- 일단 "*" 으로 모든 헤더를 사용 가능하게 두었습니다
- #92 에 이어서 CORS 관련 HOTFIX 입니다!
=> fix(CORS): CORS 설정에서 allowedHeaders 추가

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/store/api/StoreController.java, src/main/java/com/prgrms/mukvengers/domain/store/dto/request/CreateStoreRequest.java, src/main/java/com/prgrms/mukvengers/domain/store/dto/response/StoreResponse.java, src/main/java/com/prgrms/mukvengers/domain/store/model/Store.java, src/main/java/com/prgrms/mukvengers/domain/store/repository/StoreRepository.java, src/main/java/com/prgrms/mukvengers/domain/store/service/StoreService.java, src/main/java/com/prgrms/mukvengers/domain/store/service/StoreServiceImpl.java, src/main/resources/db/migration/V2.9__alter_store_table.sql, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/store/api/StoreControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/store/repository/StoreRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/store/service/StoreServiceTest.java, src/test/java/com/prgrms/mukvengers/utils/StoreObjectProvider.java, src/test/resources/schema.sql
- 가게 테이블 수정
- rating 컬럼 삭제, map_store_id -> place_id로 수정
- 카카오 api가 place_id라는 네이밍을 사용하여 place_id로 수정하였습니다
- mapStoreId가 남아있는 부분이 있는지 확인해 주세요.
- rating이 전부 삭제되었는지 확인해 주세요.
resolves #86
=> [#86] 가게 테이블 수정

src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java
- 잘못된 메서드 호출을 변경하였습니다.
resolves #94
=> [#94] Store conflict 수정 

src/main/resources/db/migration/V2.8__modify_erd_sprint3.sql
- 기존에 작성된 `V2.8_modify_erd_sprint3.sql` 파일명 `_`을 `__`으로 파일명 수정후 적용
- 신청서(proposal) 테이블 생성
- 기존 리뷰(review) 테이블 컬럼명 수정
- 추가 수정사항이 필요하다면 말씀해주세요~
resolves #91
=> [#91] 신청서(proposal) 테이블 추가 및 리뷰(review) 컬럼명 수정

src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/CreateCrewRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/CrewStatus.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/proposal/model/Proposal.java, src/main/java/com/prgrms/mukvengers/domain/proposal/model/vo/ProposalStatus.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/facade/CrewFacadeServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/CrewObjectProvider.java
- 신청서 엔티티 생성
- 신청서 상태 enum 클래스 생성
- 신청서 Repository 생성
resolves #100
=> [#100] 신청서 도메인 생성

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponse.java, src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponses.java, src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/base/ServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/utils/ProposalObjectProvider.java
- 사용자가 자신이 방장인 모임의 신청서를 조회 기능 구현, 테스트
- 추후 페이지네이션으로 변경될 수 있습니다.
- resolves #97
=> [#97] 사용자가 방장인 모임에 참여 신청이 온 신청서 조회

Dockerfile, build.gradle
- 정식 버전이 아님으로 SNAPSHOT 문구 추가
- #24
=> [#24] 운영 서버 배포전 v1.0.0 - SNAPSHOT 버전 설정하기

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/request/UpdateStatusRequest.java, src/main/java/com/prgrms/mukvengers/domain/crew/exception/CrewStatusException.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/Crew.java, src/main/java/com/prgrms/mukvengers/domain/crew/model/vo/CrewStatus.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/NotLeaderException.java, src/main/java/com/prgrms/mukvengers/global/config/security/SecurityConfig.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
- 모집 상태 변경(모집 중 -> 모집 종료)로 변경하는 기능입니다.
- 상태 변경을 위해 다음의 절차를 진행합니다.
- 모임 조회
- 모임원 조회를 모임 아이디와 유저 아이디로 조회
- 모임원의 권한이 리더인지 확인
- 모임이 모집 중 상태인지 확인
- 빼먹은 검증이 있는지 궁금합니다.
- closeStatus 라는 메서드 네이밍이 어떠신가요?
- resolves #133
=> 모집 상태 변경(모집 중-> 모집 종료) 기능

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/exception/ProposalNotFoundException.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
- 신청서 아이디로 신청서를 조회합니다.
resolves #136
=> [#136] 신청서 단건 조회 기능

src/main/java/com/prgrms/mukvengers/domain/review/api/ReviewController.java, src/main/java/com/prgrms/mukvengers/domain/review/dto/response/RevieweeListResponse.java, src/main/java/com/prgrms/mukvengers/domain/review/mapper/ReviewMapper.java, src/main/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepository.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewService.java, src/main/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImpl.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
- 리뷰를 작성하기 위한 페이지 조회 
- 모임원 정보와 해당 모임원에게 리뷰를 남겼는지 여부를 알 수 있습니다
- [feat(Review): 리뷰 페이지 DTO 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/1d0f128c90d3b61771894144149ce6714e501cb5) 
- RevieweeListResponse
- 유저 정보 및 리뷰 여부
- [feat(Review): Mapper에 toRevieweeListResponse 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/cc601f65ee9f079857332695a000206bc04a6700)  
- [feat(Review): Review를 작성했는지 확인하는 쿼리 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/fdebe219b1127382c758ef9d1795b15400e65f15) 
- ReviewRepository에 existReview 메소드 추가
- [feat(Review): getRevieweeListFromCrew 메서드 추가](https://github.com/prgrms-web-devcourse/Team-Kkini-Mukvengers-BE/commit/ed0199860f6f431a7e205c814e7d666b8ab34fbd) 
- 사용자(리뷰어: 로그인 정보)가 …
=> [#139] 리뷰 페이지 조회 기능 구현

src/main/java/com/prgrms/mukvengers/domain/crew/api/CrewController.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewDetailResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/dto/response/CrewLocationResponse.java, src/main/java/com/prgrms/mukvengers/domain/crew/mapper/CrewMapper.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewService.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/proposal/model/vo/ProposalStatus.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java
- 위경도 조회시 가게이름 반환
- 모임 조회시 사용자의 모임 신청 상태 반환
- 성능 최적화
- 복잡한 람다식
- resolves #146
=> [#146] 모임 조회 응답 필드 변경

src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/review/api/ReviewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/user/api/UserControllerTest.java
- 테스트 코드 중복을 제거했습니다.
- 중복을 더 줄일 수 있을지 궁금합니다.
- resolves #152
=> test(Crew): 테스트 코드 중복 제거

src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
- 신청서 테스트 코드 중복 코드 제거
- 제가 중복을 잘 줄였는지궁금합니다.
- resolves #154
=> Proposal api 테스트 코드 수정 

src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/exception/CrewMemberOverCapacity.java, src/main/java/com/prgrms/mukvengers/domain/proposal/exception/DuplicateProposalException.java, src/main/java/com/prgrms/mukvengers/domain/proposal/exception/ExistCrewMemberRoleException.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java
- IllegalStateException 처리한 거 Custom exception 으로 모두 수정하였습니다
- 신청서 재작성 불가능하도록 하는 검증로직 추가하였습니다!
resolves #162
=> [#162] 신청서 재작성시 Duplicate Custom exception 발생

Dockerfile, build.gradle, src/main/java/com/prgrms/mukvengers/domain/proposal/dto/response/ProposalResponse.java, src/main/java/com/prgrms/mukvengers/domain/proposal/mapper/ProposalMapper.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/GlobalExceptionHandler.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java
=> [#148] Release v1.0.1

README.md
- Architecture 그림 추가
- 실행 방법 추가
- 환경 변수
- 프로젝트 페이지 링크 
- 원하는 내용이 있다면 추가 부탁드립니다~
=> 프로젝트 단위 기간 종료 후 리드 미에 작업 사항 설명 추가

src/main/java/com/prgrms/mukvengers/domain/crew/exception/CrewNotFoundException.java, src/main/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberController.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/response/CrewMemberResponse.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/CrewMemberNotFoundException.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapper.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/test/java/com/prgrms/mukvengers/base/ControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/api/CrewControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
- 모임원 퇴장 기능 구현, 테스트
- 사용자의 아이디와 모임 아이디로 해당 모임의 모임원 삭제를 합니다.
- resolves #168
=> [#168] 모임 퇴장 기능 

src/main/java/com/prgrms/mukvengers/domain/crewmember/api/CrewMemberController.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/dto/request/UpdateCrewMemberRequest.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/exception/NotMemberException.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/model/CrewMember.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberService.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java, src/test/java/com/prgrms/mukvengers/base/ServiceTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/service/CrewServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/review/service/ReviewServiceImplTest.java
=> [#172] 모임원 강퇴 기능

settings.gradle
https://github.com/spring-projects/spring-boot/issues/30414
참고하여 settings.gradle에 pluginManagement 추가
- resolves #180
=> [#180] Github Action Error

src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/proposal/api/ProposalController.java, src/main/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepository.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalService.java, src/main/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImpl.java, src/main/java/com/prgrms/mukvengers/domain/user/exception/InvalidUserException.java, src/main/java/com/prgrms/mukvengers/global/exception/ErrorCode.java, src/main/java/com/prgrms/mukvengers/global/scheduler/Scheduler.java, src/main/resources/application.yml, src/test/java/com/prgrms/mukvengers/base/RepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/api/ProposalControllerTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/repository/ProposalRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/proposal/service/ProposalServiceImplTest.java, src/test/java/com/prgrms/mukvengers/domain/review/repository/ReviewRepositoryTest.java
- 신청서 삭제기능, 테스트, 스케줄러를 사용하여 매일 0시에 현재시간이 약속시간을 넘은 모임의 신청서 삭제
- resolves #176
=> [#176] 신청서 삭제

.github/workflows/code-review-by-chat-gpt.yml
- Open API의 chat-GPT 3.5를 이용해서 PR에 자동으로 코드리뷰를 해주는 기능 사용
- github actions에 workflow script 작성
- [참고 자료] : [Chat GPT한테 코드리뷰 시켰습니다.. (feat. Github Action)](https://velog.io/@jeonbyeongmin/Chat-GPT%ED%95%9C%ED%85%8C-%EC%BD%94%EB%93%9C%EB%A6%AC%EB%B7%B0-%EC%8B%9C%EC%BC%B0%EC%8A%B5%EB%8B%88%EB%8B%A4..-feat.-Github-Action)
=> Chat-GPT를 이용한 코드리뷰 기능 추가

src/main/generated/com/prgrms/mukvengers/domain/crewmember/mapper/CrewMemberMapperImpl.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImpl.java
- 강퇴당한 멤버는 조회, 현재인원 카운트에서 제외, 퇴장에서 누락된 Transcational 어노테이션 추가
resolves #189
=> [#189] 강퇴, 퇴장 로직 수정 

src/main/java/com/prgrms/mukvengers/domain/crew/repository/CrewRepository.java, src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java
- 내 밥모임 페이지 -> 모두 표시
- 밥모임 페이지 (가게에 열린 밥모임 리스트) -> 대기 중만 표시
resolves #195
=> [#195] 밤 모임 리스트 조회 범위 수정

src/main/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepository.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/repository/CrewMemberRepositoryTest.java, src/test/java/com/prgrms/mukvengers/domain/crewmember/service/CrewMemberServiceImplTest.java
- 강퇴, 퇴장 로직 수정 배포
- resolves #197
=> [#197] 강퇴, 퇴장 로직 수정하여 배포합니다.
